run:
  timeout: 5m
linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - gosimple
    - revive
linters-settings:
  revive:
    severity: warning
issues:
  exclude-use-default: false
